In [1]:
import numpy as np

In [2]:
np.version.version

'1.23.5'

In [3]:
arr1= np.array([2,1,3,4,77])

In [4]:
arr1[::-1]

array([77,  4,  3,  1,  2])

In [5]:
def conv2array(inpItr):
    return np.array(inpItr)

print(conv2array([21,34,1,2,3,4,5,10]))
print(conv2array((21,34,1,2,3,4,5,10)))

[21 34  1  2  3  4  5 10]
[21 34  1  2  3  4  5 10]


In [13]:
arr2= np.array([12,11])
arr3= np.array([12,44,32,45,55])
print(set(arr2))
print(set(arr3))
set(arr2).intersection(set(arr3))

{11, 12}
{32, 12, 45, 44, 55}


{12}

In [16]:
arr5= np.array([77,77])
arr6= np.array([77,66])
arr5==arr6

array([ True, False])

In [19]:
arr7= np.arange(1,21)
arr7.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [20]:
arr8= np.arange(1,101)
summ=0
for i in arr8:
    if i%3==0 and i%5==0:
        summ+=i
print(summ)

315


In [23]:
arr7.reshape(4,5).tolist()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [26]:
arr7= np.append(arr7,[21,22,23,24,25])
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [32]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

new_column = np.array([10, 11, 12])

new_arr = np.column_stack((arr, new_column))
new_arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [34]:
arr9= np.array([])
print("Empty") if len(arr9)==0 else print('Not empty')

Empty


In [39]:
arr10= np.random.randint(1,21,20).reshape(4,5)
arr10

array([[12,  3, 11,  3, 19],
       [15,  9, 18, 18, 13],
       [ 9,  1,  9,  3, 18],
       [ 1, 11,  3, 17, 12]])

In [40]:
arr10.ravel()

array([12,  3, 11,  3, 19, 15,  9, 18, 18, 13,  9,  1,  9,  3, 18,  1, 11,
        3, 17, 12])

In [41]:
import warnings

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

In [42]:
warnings.resetwarnings()

In [50]:
arr10= np.random.randint(1,21,20).reshape(4,5)
t= arr10[0].copy()
print(arr10)
arr10[0]= arr10[1].copy()
arr10[1]= t
arr10


[[17  8 20 11  2]
 [ 4 16  7  2 15]
 [ 6 17  3 12 18]
 [18  9  4  8 20]]


array([[ 4, 16,  7,  2, 15],
       [17,  8, 20, 11,  2],
       [ 6, 17,  3, 12, 18],
       [18,  9,  4,  8, 20]])

In [58]:
import numpy as np

vector = np.random.randint(1,10,10)

sorted_vector = np.sort(vector)

sorted_vector

array([1, 2, 2, 2, 4, 5, 6, 6, 6, 9])

In [61]:
ar1= np.random.randint(1,10,10)
ar2= np.random.randint(1,10,10)

np.array_equal(ar1,ar2)

False

In [63]:
print(ar1 + ar2)
print(ar1 - ar2)
print(ar1 * ar2)
print(ar1 / ar2)

[17 13 13  8  6 12 12 12  7 12]
[-1 -5  3 -6  2 -2  6 -6  1  6]
[72 36 40  7  8 35 27 27 12 27]
[0.88888889 0.44444444 1.6        0.14285714 2.         0.71428571
 3.         0.33333333 1.33333333 3.        ]


In [64]:
import datetime

today = datetime.date.today()

yesterday = today - datetime.timedelta(days=1)

tomorrow = today + datetime.timedelta(days=1)

print(today, yesterday, tomorrow)

2023-06-10 2023-06-09 2023-06-11
